Enabled: true
Output Dir: proxies
Git:
  email: felicia@realnet.ml
  name: FeliciaWen
SCServer: 127.0.0.1:25500
SCServerRemote: api.10101.io
Storage: https://realnet.ga
Template: ./template/clash
ProxyProviders:
  YahahaNPO: http://sub.yahahanpo.top/link/MPsna0K3Q1JBfwNf?mu=1
  YahahaLTD: http://yahahasub.com/link/oSmrgjMRXcAcz0O8?mu=0
  Sakura: https://subscribe.connect-node.xyz/link/qSJlYVsRF85rIGWC?sub=3
  Getfree: https://rss.getfree.win/link/WXdDzEXi5DVXpOc1?sub=1
  ADSL: https://rss.epon.cloud/link/wRa8eyB5WguX7iOM?sub=1
  ChinaG: https://a.luxury/link/cHDgH9k2VEv56gkv?clash=2
  JDYun: https://subscribe.somersaultcloud.xyz/link/PyXlvYUgoMajTtan?sub=3&extend=1
ClashProviders:
  target: clash
  list: true
  udp: true
  emoji: true
  sort: true
QuantumultXRemotes: 
  target: quanx
  list: true
Exclude:
  All: ğŸ‡¨ğŸ‡³
  region: é™é€Ÿ|æ¸¸æˆ|game
Exclude Args: 
  syntax: å¥ˆé£å°é“º|è¿‡æœŸæ—¶é—´|å‰©ä½™æµé‡|å®˜ç½‘|æœºåœº|ç»´æŠ¤
  whitelist: 
  - ChinaG
QuickGenQX: true
SmartFilter: 
  ChinaG: \d*\.*\d+(?:x|X|å€|å€ç‡)
  YahahaLTD: \d*\.*\d+(?:x|X|å€|å€ç‡)|é™é€Ÿ|Game|æ¸¸æˆ|åŸç”Ÿ|IEPL|IPLC
Rules:
  Clash:
    head: template/clash/head.yml
    rules: template/clash/connershua/rules.yml 