Enabled: true
Output Dir: proxies
Proxy Scheme: both
Git:
  email: 41898282+github-actions[bot]@users.noreply.github.com
  name: github-actions[bot]
SCServer: 127.0.0.1:25500
SCServerRemote: suc.usuc.cc
Storage: https://realnet.ga
Template: 
  Clash: ./template/clash # Directory
  Quantumult X: https://raw.githubusercontent.com/wmyfelix/Rules-For-Quantumult-X/main/Sample.conf # File
ProxyProviders:
  #YahahaNPO: http://sub.yahahanpo.top/link/MPsna0K3Q1JBfwNf?mu=1
  #ahahaLTD: http://yahahasub.top/link/2cfmpOes9QZ9mF4c?clash=1
  Sakura: https://subscribe.connect-node.net/link/qSJlYVsRF85rIGWC?clash=1
  Getfree: https://rss.getfree.win/link/WXdDzEXi5DVXpOc1?sub=1
  ADSL: https://rss.epon.cloud/link/wRa8eyB5WguX7iOM?sub=1
  ChinaG: https://a.luxury/link/cHDgH9k2VEv56gkv?clash=2
  JDYun: https://www.somersaultcloud.top/link/PyXlvYUgoMajTtan?clash=1&port=443
  #Miru: https://www.mirusubs.com/link/i5mLDM7XyzoJqJNj?sub=1
ClashProviders:
  target: clash
  list: true
  udp: true
  emoji: true
  sort: true
QuantumultXRemotes: 
  target: quanx
  list: true
Exclude:
  All: ğŸ‡¨ğŸ‡³|ğŸ‡²ğŸ‡³|é™é€Ÿ|æ¸¸æˆ|game
  region: é™é€Ÿ|æ¸¸æˆ|game
Exclude Args: 
  syntax: å¥ˆé£å°é“º|è¿‡æœŸæ—¶é—´|å‰©ä½™æµé‡|å®˜ç½‘|æœºåœº|ç»´æŠ¤
  whitelist: 
  - ChinaG
Subconverter:
  - ss
  - ssr
  - v2ray
  - clash
  - quanx
Group Classify: 
  ChinaG: \d*\.*\d+(?:x|X|å€|å€ç‡)
  #YahahaLTD: é™é€Ÿ|Game|æ¸¸æˆ
  Sakura: BT
Rules:
  Clash:
    head: template/clash/head.yml
    rules: template/clash/dler/rules.yml 
