Enabled: true
Output Dir: proxies
Git:
  email: felicia@realnet.ml
  name: FeliciaWen
SCServer: 127.0.0.1:25500
SCServerRemote: suc.usuc.cc
Storage: https://clashaddons.pages.dev
Template: 
  Clash: ./template/clash # Directory
  Quantumult X: https://raw.githubusercontent.com/wmyfelix/Rules-For-Quantumult-X/main/Sample.conf # File
ProxyProviders:
  ss: https://proxypoolss.fly.dev/ss/sub
  ss-sip002: https://proxypoolss.fly.dev/sip002/sub
  ssr: https://proxypoolss.fly.dev/ssr/sub
  vmess: https://proxypoolss.fly.dev/vmess/sub
  trojan: https://proxypoolss.fly.dev/trojan/sub
ClashProviders:
  target: clash
  list: true
  udp: true
  emoji: true
  sort: true
QuantumultXRemotes: 
  target: quanx
  list: true
Exclude:
  All: ğŸ‡¨ğŸ‡³
  region: é™é€Ÿ|æ¸¸æˆ|game
Exclude Args: 
  syntax: å¥ˆé£å°é“º|è¿‡æœŸæ—¶é—´|å‰©ä½™æµé‡|å®˜ç½‘|æœºåœº|ç»´æŠ¤
  whitelist: 
  - ChinaG
Subconverter:
  - ss
  - ssr
  - v2ray
  - clash
  - quanx
#Group Classify: 
#  name1: \d*\.*\d+(?:x|X|å€|å€ç‡)
#  name2: \d*\.*\d+(?:x|X|å€|å€ç‡)|é™é€Ÿ|Game|æ¸¸æˆ|åŸç”Ÿ|IEPL|IPLC
Rules:
  Clash:
    head: template/clash/head.yml
    rules: template/clash/connershua/rules.yml 