name: Update Provider

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
      branches:
          - OMC
  schedule:
      - cron: '20 12,18 * * *'
  watch:
      types: 
          - started
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  UpdateProviders:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Deploy SubConverter
      run: |
        cd ~
        curl -SsL https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz -o subconverter.tar.gz
        tar -xzf subconverter.tar.gz
        cd subconverter
        nohup ./subconverter > "$GITHUB_WORKSPACE"/SC.log &
    - name: Checkout This Repo
      uses: actions/checkout@v2
      with:
        path: exec
    - name: Checkout Deploy Repo
      uses: actions/checkout@v2
      with:
        repository: 'wmyfelix/OMC'
        path: deploy
        token: ${{ secrets.TOKEN }}
    - name: Convert Providers
      run: |
        cd exec
        python smart.py
    - name: Commit & push
      run: | 
        cp -r exec/proxies deploy
        cd deploy
        bash ../exec/check_commit.sh
        git push
